### ISSUE TITLE
status of the nipopy doc on the neurobagel website?

### ISSUE THREAD

**Issue by Remi-Gau** [nipoppy/nipoppy#219]

**Comment by michellewang** [comment]
Merging [this](https://github.com/neurobagel/documentation/pull/193) now!

**Comment by michellewang** [comment]
Closing since the Neurobagel docs have been updated to have a top-level note on the new documentation website (@Remi-Gau feel free to re-open if there were other things you wanted to discuss)

**Comment by Remi-Gau** [comment]
everything good with me
