### ISSUE TITLE
Remove old legacy scripts in `nipoppy`

### ISSUE THREAD

**Issue by michellewang** [nipoppy/nipoppy#304]
- [x] Delete `./nipoppy`
- [x] Move contents of `./nipoppy_cli` to `.`
  - ~Possibly rename `./nipoppy_cli/nipoppy` to `./src/nipoppy`? Not sure what the best practices are for this~
- [x] Fix paths so that CI runs correctly for tests and docs
- [x] Update pre-commit config to remove `nipoppy/.*` (see comment in #311)

**Comment by mathdugre** [comment]
- related to #210
