### ISSUE TITLE
Enforce pre-commit hooks through GH actions

### ISSUE THREAD

**Issue by mathdugre** [nipoppy/nipoppy#310]
https://github.com/pre-commit/action

**Comment by michellewang** [comment]
Good idea!

**Comment by Remi-Gau** [comment]
easier: subscribe to https://pre-commit.ci/

it will run pre-commit in CI for you automatically: it autodetects the pre-commit config

no need for extra github workflows and it will update the config when new version of each hook comes out

**Comment by mathdugre** [comment]
I agree that https://pre-commit.ci/ would be an easier alternative.

**Comment by Remi-Gau** [comment]
> subscribe to https://pre-commit.ci/

done

we can always revert it if we do not like it

**Comment by michellewang** [comment]
Closing since we now have pre-commit CI
