### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by Remi-Gau** [nipoppy/nipoppy#315]
With the work on the release I realize there is no changelog.

Some of the options:
- just rely on the github release
- manually curated changelog
- automation based on the PRs header + content
- using dedicated tools like towncrier or similar

Not urgent but probably something to be added at some point.

**Comment by Remi-Gau** [comment]
your workflow does create a github release but does not add any note to it, right?

so after the release the github release would have to be manually updated with the release notes

**Comment by mathdugre** [comment]
GitHub has a automated way to do the changelog: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by Remi-Gau** [comment]
where ever we decide the release notes live in the end, we should at least have a link to them in the doc
