### ISSUE TITLE
typo for mriqc tracker

### ISSUE THREAD

**Issue by Remi-Gau** [nipoppy/nipoppy#329]
`_*_` should be replaced by `*_` otherwise files like `sub-01_ses-test_T1w.html` won't be found.

https://github.com/nipoppy/nipoppy/blob/8430fc18c21f7bba899ac1b9313fd923ba71dd17/nipoppy_cli/nipoppy/data/examples/sample_tracker_configs/mriqc-23.1.0.json#L5-L6

**Comment by michellewang** [comment]
- Duplicate of #280 !
- Fixed in #299

**Comment by Remi-Gau** [comment]
had not realized
