### ISSUE TITLE
[BUG] nipoppy doc page side menu refers to `bidsify` command as `convert` 

### ISSUE THREAD

**Issue by nikhil153** [nipoppy/nipoppy#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Documentation side menu should say `bidsify` i.e. the title of [bidsify.md](https://github.com/nipoppy/nipoppy/blob/main/nipoppy_cli/docs/source/cli_reference/bidsify.md)

### Current Behavior

Documentation side menu says `convert` 

### Environment

- OS:
- Python version:

### Version

- version:

**Comment by michellewang** [comment]
@jbpoline this is a very easy one if you wanted to try :)

The line to change is in `docs/source/cli_reference/bidsify.md`: 

https://github.com/nipoppy/nipoppy/blob/bf185680e5fb0322584bde6a269b583918879129/docs/source/cli_reference/bidsify.md?plain=1#L1

It should be `bidsify` instead of `convert`
