### ISSUE TITLE
Support fmriprep >= 23.2.x

### ISSUE THREAD

**Issue by Remi-Gau** [nipoppy/nipoppy#351]
23.2.0 was the first version to support the 'level' CLI feature to only compute minimal derivatives to be more hard drive friendly.

https://fmriprep.org/en/stable/changes.html#january-10-2024

Nippopy could make the minimal level it's default from this version onward but also add another invocation to easily generate the required extra derivatives.

Could also simplify nipoppy users who want to work with recent openneuro datasets that only have a minimal output.

**Comment by Remi-Gau** [comment]
Realizing that my suggestion implies having several invocations for pipelines that do not have several steps.

Not sure how this is supposed to be handled.

**Comment by michellewang** [comment]
@Remi-Gau do you mean the "fit-transform" implementation of fMRIPrep?

From my understanding this is not incompatible with the multiple step approach, where the first step would be to generate the minimal derivatives and the second to have everything (since the second depends on the first one).

**Comment by Remi-Gau** [comment]
Yes that's pretty much what I meant.
True that in this case we could use a 2 step approach but this may not generaliwellze if users want to have 2 invocations with different parameters in them, no?

**Comment by michellewang** [comment]
Right, that's true. Currently there is not a great way to handle this type of use-case beyond naming invocations differently and manually changing the global config or pretending they are different steps/versions.

For multiverse-type analyses it would make sense to store outputs in different subdirectories depending on e.g. a hash of the invocation, but that would make things harder to read. Not sure what the best way to do this would be.

**Comment by Remi-Gau** [comment]
Will close as the main feature I was looking for in 23.2.x is in 24.1.1.
