### ISSUE TITLE
`run_reconall` seems confusingly named:

### ISSUE THREAD

**Issue by surchs** [nipoppy/nipoppy#397]
It seems the fmriprep descriptor argument to skip freesurfer recon-all is called `run_reconall`:

https://github.com/nipoppy/nipoppy/blob/33961a1c3dc8f45ab9427d95b971122f57b66bff/nipoppy/data/descriptors/fmriprep-23.1.3.json#L515-L523

Might be better to call this something else, maybe `skip_reconall`.

**Comment by michellewang** [comment]
Indeed, this should be renamed. The descriptor is generated ~automatically based on the `argparse` parser, so this might be due to some negation operations happening when parsing the command-line arguments.
