### ISSUE TITLE
[BUG] Fix - nipoppy dev

### ISSUE THREAD

**Issue by nikhil153** [nipoppy/nipoppy#405]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

- in person work

### Current Behavior

- remote work 

### Error message

- congestion 
- allergies 

### Environment

Sunny weather, McGill reservoir 

### How to reproduce

Try outdoor yoga again

### Anything else?

- [ ] medication 
- [x] sleep
- [x] feel better

**Comment by michellewang** [comment]
😮
