### ISSUE TITLE
Set up testing with GitHub actions

### ISSUE THREAD

**Issue by michellewang** [nipoppy/nipoppy#69]
Using a toy dataset, run some tests once every week with GitHub actions. Need to decide exactly what to test.

**Comment by Remi-Gau** [comment]
Depending on what needs to be tested, we could use some of nilearn's utility functions to create dummy BIDS and fmriprep datasets.

**Comment by surchs** [comment]
Oh, that sounds interesting. Could you point me to these functions @Remi-Gau? I think that could be helpful in many contexts

**Comment by Remi-Gau** [comment]
Note those are very rudimentary dummy datasets very much tailored for nilearn uses, so it may be missing a lot of things that may be useful for neurobagel and mr_proc.

https://github.com/nilearn/nilearn/blob/main/nilearn/_utils/data_gen.py#L838

Also those are private functions, so the API may change without warning.

**Comment by Remi-Gau** [comment]
@michellewang and @nikhil153 
would have time tomorrow to brief me on your expectations on this?
we could try to set up a roadmap to see what are the most urgent / needed things on testing and automation.

**Comment by michellewang** [comment]
I'm free tomorrow, would be great to start discussing this!

**Comment by Remi-Gau** [comment]
to keep track of those in case we need them...

DICOMs and where to find thems...

not sure it will be used but in case someone asks...

- https://github.com/effigies/nitest-dicom/tree/2246c9272658693c02810836bdf820c1c6607624
- https://github.com/neurolabusc/dcm_qa_pdt2/tree/main
- https://github.com/datalad/example-dicom-functional

**Comment by michellewang** [comment]
Closing since we have had CI unit tests for a while now. We don't have system tests checking that pipelines are invoked correctly but that might be out of scope for Nipoppy if we are moving default pipeline configurations to the pipeline catalog
